/**
 * Generated by scripts/generate-recipes-module.mjs from src/recipes/page-recipes. Do not edit.
 * Change a recipe's YAML file, then run pnpm recipes:generate.
 */

import type { PageRecipe } from './index.js';

/** Every page recipe, sorted by name. */
export const PAGE_RECIPES: readonly PageRecipe[] = [
  {
    name: 'architecture-review',
    summary:
      'Context, components, flows, trade-offs, risks and review findings for a system design.',
    useCases: [
      'design review before build',
      'service architecture overview',
      'RFC or ADR companion page',
    ],
    blocks: [
      'callout',
      'code-review',
      'comparison',
      'data-table',
      'hero',
      'key-value',
      'main-aside',
      'risk-matrix',
      'steps',
    ],
    spec: `version: 1
meta:
  title: Replace with the system name — architecture review
  description: Replace with the scope of this review.
theme:
  preset: blueprint
datasets:
  components:
    - { name: Gateway, layer: Edge, owner: Platform, tech: Envoy, status: stable }
    - { name: Orders API, layer: Service, owner: Commerce, tech: Go, status: stable }
    - { name: Pricing, layer: Service, owner: Commerce, tech: Kotlin, status: changing }
    - { name: Event bus, layer: Data, owner: Platform, tech: Kafka, status: stable }
    - { name: Ledger DB, layer: Data, owner: Finance, tech: Postgres, status: new }
blocks:
  - type: hero
    eyebrow: Architecture review
    title: Replace with the decision this design supports
    description: Replace with the problem and the constraints.
  - type: main-aside
    blocks:
      - type: data-table
        title: Components
        dataRef: components
        columns:
          - { key: name, label: Component }
          - { key: layer, label: Layer }
          - { key: owner, label: Owner }
          - { key: tech, label: Tech }
          - { key: status, label: Status, type: badge, tones: { stable: success, changing: warning, new: info } }
      - type: steps
        title: Request flow
        items:
          - { title: Gateway authenticates, text: Replace with what happens at the edge. }
          - { title: Orders API validates, text: Replace with the synchronous work. }
          - { title: Event bus fans out, text: Replace with the asynchronous work. }
    aside:
      - type: key-value
        title: Review facts
        items:
          - { key: Status, value: Replace with draft or approved }
          - { key: Reviewers, value: Replace with names }
          - { key: Decision due, value: Replace with a date }
      - type: callout
        tone: info
        title: Out of scope
        text: Replace with what this review does not cover.
  - type: comparison
    title: Trade-offs
    left: { label: Chosen — event-driven, items: [Replace with a benefit, Replace with a cost] }
    right: { label: Rejected — synchronous calls, items: [Replace with a benefit, Replace with a cost] }
  - type: risk-matrix
    title: Risks
    items:
      - { area: Event ordering, impact: high, likelihood: medium, note: Replace with the mitigation. }
      - { area: Ledger migration, impact: high, likelihood: low, note: Replace with the mitigation. }
      - { area: Team load, impact: medium, likelihood: medium, note: Replace with the mitigation. }
  - type: code-review
    title: Findings
    items:
      - { kind: good, title: Replace with a strength, text: Replace with why it holds up. }
      - { kind: concern, title: Replace with a concern, text: Replace with the evidence and the ask. }
      - { kind: question, title: Replace with an open question, text: Replace with who should answer it. }
`,
  },
  {
    name: 'benchmark-report',
    summary:
      'Baseline vs candidate verdicts, a per-run chart and table from one dataset, method and sources.',
    useCases: [
      'performance regression check',
      'model or library comparison',
      'before/after optimisation report',
    ],
    blocks: ['benchmark-comparison', 'chart', 'data-table', 'hero', 'references', 'tabs'],
    spec: `version: 1
meta:
  title: Replace with the benchmark title
  description: Replace with what was measured and why.
theme:
  preset: data-console
datasets:
  runs:
    - { case: cold start, build: baseline, ms: 412 }
    - { case: cold start, build: candidate, ms: 288 }
    - { case: warm start, build: baseline, ms: 96 }
    - { case: warm start, build: candidate, ms: 81 }
    - { case: large file, build: baseline, ms: 1840 }
    - { case: large file, build: candidate, ms: 1210 }
    - { case: many files, build: baseline, ms: 2630 }
    - { case: many files, build: candidate, ms: 2710 }
    - { case: incremental, build: baseline, ms: 154 }
    - { case: incremental, build: candidate, ms: 98 }
blocks:
  - type: hero
    eyebrow: Benchmark
    title: Replace with the headline result
    description: Replace with one sentence on the setup and the outcome.
  - type: benchmark-comparison
    title: Summary
    baseline: { label: v1.4 baseline }
    candidate: { label: v1.5 candidate }
    metrics:
      - { label: p50 latency, baseline: 154, candidate: 98, better: lower, format: duration }
      - { label: Peak memory, baseline: 512, candidate: 468, better: lower, unit: MB }
      - { label: Throughput, baseline: 1180, candidate: 1525, better: higher, unit: req/s }
      - { label: Bundle size, baseline: 84, candidate: 86, better: lower, unit: kB }
    method: Replace with the machine, dataset, run count and how outliers were handled.
    limitations: Replace with what this benchmark does not cover.
  - type: tabs
    items:
      - title: Chart
        blocks:
          - type: chart
            kind: bar
            title: Latency per case
            dataRef: runs
            x: { field: case }
            y: { field: ms, label: Time, format: duration }
            series: { field: build }
      - title: Table
        blocks:
          - type: data-table
            dataRef: runs
            columns:
              - { key: case, label: Case }
              - { key: build, label: Build, type: badge, tones: { candidate: info } }
              - { key: ms, label: Time, type: number, format: duration }
  - type: references
    title: Sources
    items:
      - { id: harness, title: Replace with the benchmark harness, source: Repository README, year: 2026 }
      - { id: raw, title: Replace with the raw results file, note: Replace with where the raw numbers live. }
`,
  },
  {
    name: 'case-study',
    summary:
      'Customer story with context, approach, measured before/after results, a quote and the team.',
    useCases: ['customer case study', 'internal project retrospective', 'migration success story'],
    blocks: ['card', 'chart', 'hero', 'kpi', 'people', 'split', 'steps', 'testimonial'],
    spec: `version: 1
meta:
  title: Replace with the customer — case study
  description: Replace with the one-line outcome.
theme:
  preset: product-studio
datasets:
  results:
    - { month: Jan, hours: 42 }
    - { month: Feb, hours: 39 }
    - { month: Mar, hours: 24 }
    - { month: Apr, hours: 15 }
    - { month: May, hours: 11 }
    - { month: Jun, hours: 9 }
blocks:
  - type: hero
    eyebrow: Case study
    title: Replace with the result in one line
    description: Replace with who the customer is and what they needed.
  - type: kpi
    items:
      - { label: Manual hours per week, value: '9', delta: '-79%', trend: down, good: down }
      - { label: Release frequency, value: Daily, delta: was weekly, trend: up, good: up }
      - { label: Payback, value: 4 months }
  - type: split
    blocks:
      - type: card
        title: Challenge
        text: |-
          Replace with the situation before: the problem, its cost and why it mattered.

          Replace with what the team tried first and why it fell short.
      - type: steps
        title: Approach
        items:
          - { title: Replace with step one, text: Replace with what was done. }
          - { title: Replace with step two, text: Replace with what was done. }
          - { title: Replace with step three, text: Replace with what was done. }
  - type: chart
    kind: area
    title: Manual hours per week
    dataRef: results
    x: { field: month }
    y: { field: hours, label: Hours, min: 0 }
    markers:
      - { x: Mar, label: Rollout }
  - type: testimonial
    items:
      - { quote: Replace with the customer quote that sums up the result., name: Replace with a name, role: Replace with role and company }
  - type: people
    title: Team
    items:
      - { name: Replace with a name, role: Replace with a role, bio: Replace with one line on their part. }
      - { name: Replace with a name, role: Replace with a role, bio: Replace with one line on their part. }
`,
  },
  {
    name: 'dashboard',
    summary:
      'KPI strip, trend and mix charts, and a filterable service table over shared datasets.',
    useCases: ['weekly metrics review', 'service health overview', 'product analytics snapshot'],
    blocks: [
      'chart',
      'data-table',
      'filter-bar',
      'grid',
      'grid-item',
      'hero',
      'kpi',
      'metric-breakdown',
      'select',
      'text-input',
    ],
    spec: `version: 1
meta:
  title: Replace with the dashboard title
  description: Replace with one line on what this dashboard tracks.
theme:
  preset: data-console
datasets:
  weekly:
    - { week: W1, requests: 182000 }
    - { week: W2, requests: 196000 }
    - { week: W3, requests: 211000 }
    - { week: W4, requests: 238000 }
  services:
    - { service: api, owner: Platform, p95: 182, uptime: 99.95, status: healthy }
    - { service: auth, owner: Identity, p95: 96, uptime: 99.99, status: healthy }
    - { service: search, owner: Discovery, p95: 410, uptime: 99.2, status: degraded }
    - { service: billing, owner: Payments, p95: 240, uptime: 99.9, status: healthy }
    - { service: export, owner: Platform, p95: 880, uptime: 98.7, status: down }
blocks:
  - type: hero
    eyebrow: Replace with a team or product
    title: Replace with the dashboard headline
    description: Replace the sample rows in datasets with your own numbers.
  - type: kpi
    items:
      - { label: Requests, value: 238k, delta: '+12.8%', trend: up, good: up, series: [182, 196, 211, 238] }
      - { label: Error rate, value: '0.63%', delta: '-0.6 pt', trend: down, good: down, series: [1.15, 0.92, 1.23, 0.63] }
      - { label: p95 latency, value: 182 ms, delta: '-14 ms', trend: down, good: down }
      - { label: Uptime, value: '99.9%', delta: flat, trend: flat }
  - type: grid
    blocks:
      - type: grid-item
        span: 8
        tabletSpan: 12
        blocks:
          - type: chart
            kind: line
            title: Replace with the trend title
            dataRef: weekly
            x: { field: week }
            y: { field: requests, label: Requests, format: compact, min: 0 }
      - type: grid-item
        span: 4
        tabletSpan: 12
        blocks:
          - type: metric-breakdown
            title: Traffic by client
            format: compact
            parts:
              - { label: Web, value: 128400 }
              - { label: Mobile, value: 73500 }
              - { label: Partner API, value: 36100 }
  - type: filter-bar
    target: services-table
    blocks:
      - { type: select, label: Status, field: status, optionsFrom: status }
      - { type: text-input, label: Service, field: service, match: contains }
  - type: data-table
    id: services-table
    title: Replace with the table title
    dataRef: services
    columns:
      - { key: service, label: Service }
      - { key: owner, label: Owner }
      - { key: p95, label: p95, type: number, unit: ms }
      - { key: uptime, label: Uptime, type: percent, decimals: 2 }
      - { key: status, label: Status, type: badge, tones: { healthy: success, degraded: warning, down: danger } }
`,
  },
  {
    name: 'decision-memo',
    summary:
      'Recommendation first, then context, an options table, trade-offs, risks and next steps.',
    useCases: ['decision record for leadership', 'build vs buy memo', 'vendor or tool selection'],
    blocks: [
      'callout',
      'checklist',
      'comparison',
      'data-table',
      'hero',
      'key-value',
      'risk-matrix',
    ],
    spec: `version: 1
meta:
  title: Replace with the decision — memo
  description: Replace with the decision being asked for.
theme:
  preset: executive-report
datasets:
  options:
    - { option: Replace with option A, cost: 120000, months: 3, risk: low, pick: recommended }
    - { option: Replace with option B, cost: 45000, months: 6, risk: medium, pick: viable }
    - { option: Replace with option C, cost: 0, months: 2, risk: high, pick: rejected }
blocks:
  - type: hero
    eyebrow: Decision memo · Replace with the date
    title: Replace with the recommendation in one sentence
    description: Replace with who decides and by when.
  - type: callout
    tone: success
    title: Recommendation
    text: Replace with the option you recommend and the single strongest reason.
  - type: key-value
    title: Context
    items:
      - { key: Problem, value: Replace with what forces a decision now }
      - { key: Constraint, value: Replace with the budget and deadline }
      - { key: Owner, value: Replace with the accountable person }
  - type: data-table
    title: Options
    dataRef: options
    columns:
      - { key: option, label: Option }
      - { key: cost, label: Cost, type: currency, currency: USD, decimals: 0 }
      - { key: months, label: Time, type: number, unit: months }
      - { key: risk, label: Risk, type: badge, tones: { low: success, medium: warning, high: danger } }
      - { key: pick, label: Verdict, type: badge, tones: { recommended: success, viable: info, rejected: neutral } }
  - type: comparison
    title: Trade-offs
    left: { label: If we choose A, items: [Replace with a gain, Replace with a cost] }
    right: { label: If we wait, items: [Replace with a gain, Replace with a cost] }
  - type: risk-matrix
    title: Risks of the recommendation
    items:
      - { area: Replace with a risk, impact: high, likelihood: low, note: Replace with the mitigation. }
      - { area: Replace with a risk, impact: medium, likelihood: medium, note: Replace with the mitigation. }
  - type: checklist
    title: Next steps
    items:
      - { text: Replace with the first action and its owner }
      - { text: Replace with the second action and its owner }
`,
  },
  {
    name: 'implementation-plan',
    summary:
      'Goal, scope, phased roadmap, step-by-step work, a task board, risks and the definition of done.',
    useCases: ['feature implementation plan', 'migration plan', 'project kickoff brief'],
    blocks: ['checklist', 'comparison', 'hero', 'kanban', 'risk-matrix', 'roadmap', 'steps'],
    spec: `version: 1
meta:
  title: Replace with the project name — implementation plan
  description: Replace with the goal in one line.
theme:
  preset: swiss-clean
datasets:
  tasks:
    - { title: Replace with a task, column: todo, owner: Backend, status: phase 2 }
    - { title: Replace with a task, column: todo, owner: Frontend, status: phase 3 }
    - { title: Replace with a task, column: doing, owner: Backend, status: phase 1 }
    - { title: Replace with a task, column: done, owner: QA, status: phase 1 }
blocks:
  - type: hero
    eyebrow: Implementation plan
    title: Replace with the outcome this plan delivers
    description: Replace with the problem, the constraint and the deadline.
  - type: comparison
    title: Scope
    left: { label: In scope, items: [Replace with a deliverable, Replace with a deliverable] }
    right: { label: Out of scope, items: [Replace with a non-goal, Replace with a non-goal] }
  - type: roadmap
    title: Phases
    periods: [Week 1, Week 2, Week 3, Week 4, Week 5, Week 6]
    items:
      - { title: Replace with phase 1, start: Week 1, end: Week 2, status: active }
      - { title: Replace with phase 2, start: Week 3, end: Week 4, status: planned }
      - { title: Replace with phase 3, start: Week 5, end: Week 6, status: planned }
  - type: steps
    title: Phase 1 steps
    items:
      - { title: Replace with the first step, text: Replace with the files or systems it touches. }
      - { title: Replace with the second step, text: Replace with how it is verified. }
      - { title: Replace with the third step, text: Replace with the rollback if it fails. }
  - type: kanban
    title: Tasks
    dataRef: tasks
    columns:
      - { id: todo, title: To do }
      - { id: doing, title: In progress }
      - { id: done, title: Done }
  - type: risk-matrix
    title: Risks
    items:
      - { area: Replace with a risk, impact: high, likelihood: low, note: Replace with the mitigation. }
      - { area: Replace with a risk, impact: medium, likelihood: medium, note: Replace with the mitigation. }
  - type: checklist
    title: Definition of done
    items:
      - { text: Replace with an acceptance criterion }
      - { text: Replace with an acceptance criterion }
      - { text: Tests and docs updated }
`,
  },
  {
    name: 'incident-report',
    summary:
      'Impact summary, timeline, error log, root cause, failing checks and follow-up board for a postmortem.',
    useCases: [
      'incident postmortem',
      'outage summary for leadership',
      'service degradation review',
    ],
    blocks: ['callout', 'hero', 'kanban', 'log-viewer', 'stats', 'test-results', 'timeline'],
    spec: `version: 1
meta:
  title: Replace with the incident name
  description: Replace with a one-line incident summary.
theme:
  preset: executive-report
datasets:
  followups:
    - { title: Add a canary for config pushes, column: todo, owner: Platform, status: P1 }
    - { title: Alert on queue depth, column: doing, owner: SRE, status: P1 }
    - { title: Document the rollback runbook, column: doing, owner: On-call, status: P2 }
    - { title: Roll back the bad config, column: done, owner: On-call, status: P0 }
blocks:
  - type: hero
    eyebrow: Incident report · Replace with the severity
    title: Replace with what users experienced
    description: Replace with the duration, the blast radius and the current state.
  - type: stats
    items:
      - { label: Duration, value: 47 min }
      - { label: Users affected, value: '12%' }
      - { label: Failed requests, value: 38.2k }
      - { label: Time to detect, value: 6 min }
  - type: timeline
    title: Timeline
    items:
      - { when: '09:12', title: Config change deployed, text: Replace with what changed. }
      - { when: '09:18', title: Alert fired, text: Replace with how it was detected. }
      - { when: '09:31', title: Cause identified, text: Replace with the finding. }
      - { when: '09:59', title: Recovered, text: Replace with the fix that restored service. }
  - type: log-viewer
    title: Key log lines
    lines:
      - { time: '09:12:04', level: info, source: deploy, message: Replace with the config push line }
      - { time: '09:17:51', level: warn, source: api, message: Replace with the first warning }
      - { time: '09:18:02', level: error, source: api, message: Replace with the error users hit }
  - type: callout
    tone: warning
    title: Root cause
    text: Replace with the root cause in two or three plain sentences.
  - type: test-results
    title: Checks that should have caught it
    suites:
      - name: Replace with a suite name
        cases:
          - { name: Replace with the check that failed, status: fail, message: Replace with why it missed the fault. }
          - { name: Replace with a check that passed, status: pass, duration: 120 }
  - type: kanban
    title: Follow-ups
    dataRef: followups
    columns:
      - { id: todo, title: To do }
      - { id: doing, title: In progress }
      - { id: done, title: Done }
`,
  },
  {
    name: 'product-showcase',
    summary:
      'Launch page with hero, feature bento, plan comparison, pricing, quotes and a call to action.',
    useCases: ['product or feature launch', 'landing page draft', 'internal tool announcement'],
    blocks: ['bento', 'cta', 'feature-matrix', 'hero', 'pricing', 'testimonial'],
    spec: `version: 1
meta:
  title: Replace with the product name
  description: Replace with the one-line value proposition.
theme:
  preset: product-studio
blocks:
  - type: hero
    eyebrow: Replace with a launch label
    title: Replace with the promise in six words
    description: Replace with who it is for and the outcome they get.
    align: center
  - type: bento
    items:
      - { eyebrow: Speed, title: Replace with the headline feature, text: Replace with the benefit in one sentence., value: 3x, size: large }
      - { title: Replace with a second feature, text: Replace with the benefit., size: wide }
      - { title: Replace with a third feature, text: Replace with the benefit. }
      - { title: Replace with a fourth feature, text: Replace with the benefit. }
  - type: feature-matrix
    title: Compare plans
    plans: [Starter, Team, Enterprise]
    rows:
      - { feature: Replace with feature A, values: [true, true, true] }
      - { feature: Replace with feature B, values: [false, true, true] }
      - { feature: Replace with feature C, values: [false, false, true] }
      - { feature: Seats, values: ['1', Up to 25, Unlimited] }
  - type: pricing
    plans:
      - name: Starter
        price: 0
        currency: USD
        period: month
        summary: Replace with who Starter is for.
        features: [Replace with a feature, Replace with a limit]
        cta: { label: Start free, href: '#start' }
      - name: Team
        price: 24
        currency: USD
        period: month
        highlight: true
        summary: Replace with who Team is for.
        features: [Everything in Starter, Replace with a feature]
        cta: { label: Start a trial, href: '#trial' }
      - name: Enterprise
        price: Custom
        summary: Replace with who Enterprise is for.
        features: [Everything in Team, Replace with a feature]
        cta: { label: Contact sales, href: '#contact' }
  - type: testimonial
    items:
      - { quote: Replace with a short customer quote about the outcome., name: Replace with a name, role: Replace with role and company }
      - { quote: Replace with a second quote about a different benefit., name: Replace with a name, role: Replace with role and company }
  - type: cta
    title: Replace with the closing call to action
    text: Replace with the reason to act now.
    actions:
      - { label: Get started, href: '#start', variant: primary }
      - { label: Read the docs, href: '#docs', variant: secondary }
`,
  },
  {
    name: 'release-recap',
    summary:
      'Release highlights, numbers, changed files, a test summary, upgrade notes and what comes next.',
    useCases: ['release notes page', 'sprint or milestone recap', 'changelog for stakeholders'],
    blocks: [
      'callout',
      'card-grid',
      'diff-summary',
      'hero',
      'list',
      'stats',
      'tabs',
      'test-results',
    ],
    spec: `version: 1
meta:
  title: Replace with the product and version — release recap
  description: Replace with the release in one line.
theme:
  preset: editorial
blocks:
  - type: hero
    eyebrow: Release · Replace with the version
    title: Replace with the theme of this release
    description: Replace with who benefits and what changes for them.
  - type: stats
    items:
      - { label: Pull requests, value: '48' }
      - { label: Contributors, value: '11' }
      - { label: Issues closed, value: '63' }
      - { label: Breaking changes, value: '1' }
  - type: card-grid
    title: Highlights
    items:
      - { title: Replace with highlight one, text: Replace with what users can do now. }
      - { title: Replace with highlight two, text: Replace with what got faster or simpler. }
      - { title: Replace with highlight three, text: Replace with what got fixed. }
  - type: tabs
    items:
      - title: Changes
        blocks:
          - type: diff-summary
            items:
              - { path: src/replace/with-a-file.ts, status: added, additions: 214 }
              - { path: src/replace/with-another.ts, status: modified, additions: 38, deletions: 12 }
              - { path: src/replace/old-module.ts, status: deleted, deletions: 140 }
      - title: Tests
        blocks:
          - type: test-results
            coverage: 87
            suites:
              - name: Replace with a suite
                cases:
                  - { name: Replace with a test, status: pass, duration: 42 }
                  - { name: Replace with a test, status: pass, duration: 18 }
                  - { name: Replace with a flaky test, status: flaky, duration: 230 }
  - type: callout
    tone: warning
    title: Upgrade notes
    text: Replace with the breaking change and the one step users must take.
  - type: list
    title: Next up
    items:
      - { text: Replace with a planned item, badge: next }
      - { text: Replace with a planned item, badge: later }
`,
  },
  {
    name: 'research-report',
    summary:
      'Abstract, study facts in a sidebar, findings with a chart and breakdown, methods, limits and references.',
    useCases: ['research write-up', 'experiment or A/B test report', 'literature or market review'],
    blocks: [
      'accordion',
      'callout',
      'chart',
      'hero',
      'key-value',
      'metric-breakdown',
      'references',
      'rich-text',
      'sidebar-layout',
    ],
    spec: `version: 1
meta:
  title: Replace with the study title
  description: Replace with the research question in one line.
theme:
  preset: research-notebook
datasets:
  samples:
    - { group: Control, effort: 2, score: 61 }
    - { group: Control, effort: 4, score: 64 }
    - { group: Control, effort: 6, score: 70 }
    - { group: Control, effort: 8, score: 72 }
    - { group: Treatment, effort: 2, score: 66 }
    - { group: Treatment, effort: 4, score: 73 }
    - { group: Treatment, effort: 6, score: 81 }
    - { group: Treatment, effort: 8, score: 86 }
blocks:
  - type: hero
    eyebrow: Research report
    title: Replace with the main finding as a sentence
    description: Replace with the question, the sample and the method in one line.
  - type: sidebar-layout
    sidebar:
      - type: key-value
        title: Study
        items:
          - { key: Sample, value: n = 240 }
          - { key: Period, value: Jan–Mar 2026 }
          - { key: Method, value: Randomised trial }
    blocks:
      - type: rich-text
        text: |-
          Replace with the abstract: why the question matters and what was already known.

          Replace with the headline result and how confident you are in it.
      - type: callout
        tone: success
        title: Key finding
        text: Replace with the finding a reader should remember.
      - type: chart
        kind: scatter
        title: Score by effort
        dataRef: samples
        x: { field: effort, label: Effort (hours) }
        y: { field: score, label: Score }
        series: { field: group }
      - type: metric-breakdown
        title: Where the time went
        unit: h
        parts:
          - { label: Replace with phase A, value: 12 }
          - { label: Replace with phase B, value: 7 }
          - { label: Replace with phase C, value: 3 }
      - type: accordion
        items:
          - { title: Method, text: Replace with how participants were chosen and measured. }
          - { title: Limitations, text: Replace with what could bias the result. }
  - type: references
    title: References
    items:
      - { id: '1', title: Replace with a cited source, authors: Replace with authors, source: Replace with a venue, year: 2025 }
`,
  },
];
