import { describe, expect, it } from 'vitest';
import { compile } from '../../src/render/render.js';

function page(blocks: string): string {
  return `version: 1
meta:
  title: Chrome fixture
blocks:
  - type: hero
    title: Chrome fixture
${blocks}`;
}

const SECTIONS = ['Overview', 'Details', 'Risks']
  .map(
    (title) => `  - type: section
    title: ${title}
    blocks:
      - type: text
        text: Body for ${title}.`,
  )
  .join('\n');

describe('document chrome', () => {
  it('adds an outline once a page has three titled top-level sections', () => {
    const result = compile(page(SECTIONS));
    expect(result.features).toContain('outline');
    expect(result.html).toContain('<nav class="ak-toc" aria-label="On this page">');
    expect(result.html).toMatch(/<a href="#ak-sec-[^"]+" data-ak-outline-link>Risks<\/a>/u);
    expect(result.html).toContain('wireOutline();');
    // Every outline link resolves to a section on the page.
    for (const [, anchor] of result.html.matchAll(/href="#(ak-sec-[^"]+)"/gu)) {
      expect(result.html).toContain(`id="${anchor}"`);
    }
  });

  it('leaves the outline out of short pages and tree-shakes its stylesheet', () => {
    const result = compile(page(SECTIONS.split('\n  - type: section')[0] ?? ''));
    expect(result.features).not.toContain('outline');
    expect(result.html).not.toContain('.ak-toc');
    expect(result.html).not.toContain('ak-shell--outline');
  });

  it('closes every page with a deterministic colophon', () => {
    const { html } = compile(page(SECTIONS));
    expect(html).toMatch(/<footer class="ak-colophon">.*Generated by @bestagentkits\/render /su);
    expect(html).toContain('<a href="#ak-main-content">Back to top</a>');
  });

  it('gives a code block line spans and a working copy button', () => {
    const { html, features } = compile(
      page(`  - type: code
    language: ts
    title: Example
    text: |
      const a = 1;
      const b = 2;`),
    );
    expect(features).toContain('copy');
    expect(html).toMatch(
      /<button type="button" class="ak-code-copy"[^>]*data-ak-on-click="[^"]*copy[^"]*"/u,
    );
    expect(html).toContain(
      '<span class="ak-line"><span class="ak-tk-k">const</span> a = <span class="ak-tk-n">1</span>;</span>\n<span class="ak-line"><span class="ak-tk-k">const</span> b = <span class="ak-tk-n">2</span>;</span>',
    );
    expect(html).toContain('<span class="ak-code-lang">ts</span>');
  });

  it('right-aligns numeric table columns only', () => {
    const { html } = compile(
      page(`  - type: table
    title: Sizes
    columns: [Name, Bytes]
    rows:
      - [alpha, "1,024"]
      - [beta, 12%]`),
    );
    expect(html).toContain('<th scope="col" class="ak-num">Bytes</th>');
    expect(html).toContain('<th scope="col">Name</th>');
    expect(html).toContain('<td class="ak-num">1,024</td>');
  });
});
