import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { compile } from '../../src/render/render.js';
import { themePresetNames } from '../../src/theme/load-theme.js';

const showcase = fileURLToPath(
  new URL('../../fixtures/pages/theme-showcase.yaml', import.meta.url),
);
const snapshotDir = fileURLToPath(new URL('../../fixtures/snapshots', import.meta.url));
const spec = readFileSync(showcase, 'utf8');
const presets = themePresetNames();

/**
 * Cross-preset snapshots.
 *
 * The committed files are the artifact a reviewer reads. Regenerating them here
 * proves the compiler still produces exactly those bytes, so a theme change
 * cannot alter output without the snapshot diff showing it.
 */
describe('theme snapshots', () => {
  it('has a committed snapshot for every built-in preset', () => {
    for (const preset of presets) {
      expect(existsSync(`${snapshotDir}/theme-${preset}.html`), preset).toBe(true);
    }
  });

  it('regenerates byte-identical snapshots', () => {
    for (const preset of presets) {
      const result = compile(spec, { theme: preset, source: 'theme-showcase.yaml' });
      const committed = readFileSync(`${snapshotDir}/theme-${preset}.html`, 'utf8');
      const banner = `<!-- generated by scripts/generate-theme-snapshots.mjs: preset=${preset} hash=${result.hash} -->\n`;
      expect(committed, preset).toBe(`${banner}${result.html}`);
    }
  });

  it('renders one spec distinctly under every preset', () => {
    const hashes = new Set(presets.map((preset) => compile(spec, { theme: preset }).hash));
    expect(hashes.size).toBe(presets.length);
  });

  it('carries each preset own accent into the artifact', () => {
    const accents: Record<string, string> = {
      blueprint: '--ak-color-background:#f0f4f8',
      editorial: '--ak-color-background:#faf8f2',
      'paper-ink': '--ak-color-background:#faf6f0',
      'terminal-mono': '--ak-color-background:#f4f4ef',
      'swiss-clean': '--ak-color-background:#ffffff',
      'warm-signal': '--ak-color-background:#fbf7f1',
    };
    for (const [preset, marker] of Object.entries(accents)) {
      expect(readFileSync(`${snapshotDir}/theme-${preset}.html`, 'utf8'), preset).toContain(marker);
    }
  });
});

describe('font policy', () => {
  const snapshots = presets.map((preset) => ({
    preset,
    html: readFileSync(`${snapshotDir}/theme-${preset}.html`, 'utf8'),
  }));

  it('bundles no fonts, so there is no font licence to carry', () => {
    for (const { preset, html } of snapshots) {
      expect(html, preset).not.toContain('@font-face');
      expect(html, preset).not.toContain('fonts.googleapis');
      expect(html, preset).not.toContain('fonts.gstatic');
      expect(html, preset).not.toContain('.woff');
      expect(html, preset).not.toMatch(/@import\s+url/iu);
    }
  });

  it('ends every font stack in a generic family so the page renders offline', () => {
    for (const { preset, html } of snapshots) {
      for (const match of html.matchAll(/--ak-font-(?:body|heading|mono):([^;}]+)/gu)) {
        expect(match[1] ?? '', preset).toMatch(/(sans-serif|serif|monospace)$/u);
      }
    }
  });

  it('references no remote resource at all in a default artifact', () => {
    for (const { preset, html } of snapshots) {
      expect(html, preset).not.toMatch(/\ssrc="https?:/iu);
      expect(html, preset).not.toContain('cdn.');
      expect(html, preset).not.toMatch(/<link[^>]+stylesheet/iu);
    }
  });
});
